# Generated by Django 4.2.15 on 2025-06-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Saime',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=1, verbose_name='Origen')),
                ('cedula', models.IntegerField(unique=True, verbose_name='Cédula')),
                ('pais_origen', models.CharField(blank=True, max_length=3, null=True, verbose_name='Pais')),
                ('nacionalidad', models.CharField(max_length=4, verbose_name='Nacionalidad')),
                ('primer_nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='S. Nombre')),
                ('primer_apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True, verbose_name='S.Apellido')),
                ('fecha_nacimiento', models.DateField(verbose_name='F. nacimiento')),
                ('naturalizado', models.SmallIntegerField(blank=True, null=True)),
                ('sexo', models.CharField(max_length=1, verbose_name='Sexo')),
                ('fecha_registro', models.CharField(blank=True, max_length=10, null=True, verbose_name='Fecha Registro')),
                ('fecha_ult_actualizacion', models.CharField(blank=True, max_length=10, null=True, verbose_name='Fecha Actualizacion')),
            ],
            options={
                'verbose_name': 'Saime',
                'verbose_name_plural': 'Saime',
                'db_table': 'saime"."saime',
                'managed': False,
            },
        ),
    ]
