# Generated by Django 4.2.15 on 2025-06-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comunidade',
            fields=[
                ('estado_me_id', models.IntegerField(blank=True, null=True, verbose_name='Estado ME ID')),
                ('municipio_me_id', models.IntegerField(blank=True, null=True, verbose_name='Municipio ME ID')),
                ('parroquia_me_id', models.IntegerField(blank=True, null=True, verbose_name='parroquia ME ID')),
                ('comunidad_me_id', models.IntegerField(blank=True, null=True, verbose_name='Comunidad ME ID')),
                ('estado_cne_id', models.IntegerField(blank=True, null=True, verbose_name='Estado CNE ID')),
                ('municipio_cne_id', models.IntegerField(blank=True, null=True, verbose_name='Municipio CNE ID')),
                ('parroquia_cne_id', models.IntegerField(blank=True, null=True, verbose_name='Parroquia CNE ID')),
                ('comunidad_cne_id', models.BigIntegerField(blank=True, null=True, verbose_name='Comunidad CNE ID')),
                ('estado_ine_id', models.IntegerField(blank=True, null=True, verbose_name='Estado INE ID')),
                ('municipio_ine_id', models.IntegerField(blank=True, null=True, verbose_name='Municipio INE ID')),
                ('parroquia_ine_id', models.IntegerField(blank=True, null=True, verbose_name='Parroquia INE ID')),
                ('comunidad_ine_id', models.BigIntegerField(blank=True, null=True, verbose_name='Comunidad INE ID')),
                ('codigo_unico_parroquia', models.IntegerField(blank=True, null=True, verbose_name='CU. Parroquia')),
                ('codigo_unico_parroquia_comunidad', models.IntegerField(blank=True, null=True, verbose_name='CU. PC')),
                ('estado_nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado')),
                ('estado_capital', models.CharField(blank=True, max_length=100, null=True, verbose_name='Capital del estado')),
                ('municipio_nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Municipio')),
                ('municipio_capital', models.CharField(blank=True, max_length=100, null=True, verbose_name='Capital del Municipio')),
                ('parroquia_nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Parroquia')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Comunidad')),
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Comunidad',
                'verbose_name_plural': 'Comunidades',
                'db_table': 'geo"."comunidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='estado ME ID')),
                ('estado_cne_id', models.IntegerField(blank=True, null=True, verbose_name='Estado CNE ID')),
                ('estado_ine_id', models.IntegerField(blank=True, null=True, verbose_name='Estado INE ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('capital', models.CharField(blank=True, max_length=100, null=True, verbose_name='Capital')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'geo"."estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('estado_me_id', models.IntegerField(blank=True, null=True, verbose_name='Estado ME ID')),
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_cne_id', models.IntegerField(blank=True, null=True, verbose_name='Estado CNE ID')),
                ('municipio_cne_id', models.IntegerField(blank=True, null=True, verbose_name='Municipio CNE ID')),
                ('estado_ine_id', models.IntegerField(blank=True, null=True, verbose_name='Estado INE ID')),
                ('municipio_ine_id', models.IntegerField(blank=True, null=True, verbose_name='Municipio INE ID')),
                ('estado_nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado')),
                ('estado_capital', models.CharField(blank=True, max_length=100, null=True, verbose_name='Capital del estado')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('capital', models.CharField(blank=True, max_length=100, null=True, verbose_name='Capital')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'db_table': 'geo"."municipio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_me_id', models.IntegerField(blank=True, null=True, verbose_name='Estado ME ID')),
                ('municipio_me_id', models.IntegerField(blank=True, null=True, verbose_name='Municipio ME ID')),
                ('parroquia_me_id', models.IntegerField(blank=True, null=True, verbose_name='Parroquia ME ID')),
                ('estado_cne_id', models.IntegerField(blank=True, null=True, verbose_name='Estado CNE ID')),
                ('municipio_cne_id', models.IntegerField(blank=True, null=True, verbose_name='Municipio CNE ID')),
                ('parroquia_cne_id', models.IntegerField(blank=True, null=True, verbose_name='Parroquia CNE ID')),
                ('estado_ine_id', models.IntegerField(blank=True, null=True, verbose_name='Estado CNE ID')),
                ('municipio_ine_id', models.IntegerField(blank=True, null=True, verbose_name='Municipio INE ID')),
                ('parroquia_ine_id', models.IntegerField(blank=True, null=True, verbose_name='Parroquia INE ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Parroquia',
                'verbose_name_plural': 'Parroquias',
                'db_table': 'geo"."parroquia',
                'managed': False,
            },
        ),
    ]
